creation_rules:
  - path_regex: sing-box/secrets/secrets(\.enc)?\.yaml$
    key_groups:
      - age:
        - &main "age1p9r276rvjh98r93nsvqhzuhlqnawur0j0hn34qmeangcd94mlchqgvm820"
  - path_regex: (traefik|element|element-call|synapse|metrics|nextcloud|jitsi|certs|coturn|wireguard|backup|system|firewall|router|i2p)/secrets/secrets(\.enc)?\.yaml$
    key_groups:
      - age:
        - &main "age1p9r276rvjh98r93nsvqhzuhlqnawur0j0hn34qmeangcd94mlchqgvm820"
  - path_regex: secrets/hosts(\.enc)?\.yaml$
    key_groups:
      - age:
        - &main "age1p9r276rvjh98r93nsvqhzuhlqnawur0j0hn34qmeangcd94mlchqgvm820"
